language: java

jdk:
  - oraclejdk11

sudo: false
env:
  global:
    #key for github
    #GITHUB_OAUTH_TOKEN
    - secure: "tiuAcas254qvm4RwQswqzvE6ui6KzNEzlYyp4r+VlGGLqY2FB0nPPV8Xlr5/sBEdL+aAuQ8q2WLUei3/rQZFhOAnb9D3tUhu8ei4X280UADfPvxXpZoDLHlgceS61mmrF4Pa4n3itudr5i6M6VSTzyjZbG9eDqXqVE6V/6wXWFj3n7erltS0XL5EM89lo/IG5U0ZOxF53GYq45W86/Q0x8dufas9Lssuz5F0YDj1EoL9GoyFh/IlCAoyazRtDq/c/Lg0YLla/E2/94xZQ8mnF20jPtuvc6EIfgUYngpqwrbiUlAP8H5W7SUTJvfwT3JR4NIC4JmC79751wni031RtxeTqwx+OonxcBChsoc6zi/w3sb2w6fFqzaSSeFmMlf2E02Trcrl19uJ7wCacnP0DLWNRlkDvLPqFJq6dhY6NpRxej0lre5kHjQFvim8vtrlqFt5txSLtSeAMzMLHZDf/A5W7sGB0AdWO39OYstLR26PWdhF5ZmLZRyO64objJDHcYLfLZl1BiQ8m7E5DMb/pLJbo8GmTOKMrUQbm3aFgH7V/z+/Vy2Ip1Z84NKQo9L1TudIsxoJlmGn6Cnd7H51BhC9ZhebpOqpLwrn2w2JYtVozk7n+pyLNtbwDC2M9W9KZ8n+SWeADAMcoik7UMUwlO15i70hkV7XQWw+IfOBUxY="
    - environment=test
    #sonatype credentials
    #OSSRH_JIRA_USERNAME
    - secure: "zvb53E9Y9Nouv4Erzl9OuGn7fYslBh/VXSfVkmr7QxGTS/sGnrTbBrS/RGkpaJg7lrixBXxT4bak6p7fhE+4W3mqhbZ1mWnxLqnPAWxScD61m7ableK9/1IDQkCfMs9GLgELYUL1xHruvpOv9FUTZk/xwuZ/mVLum085LFvwvQDFqWHC/uB4K6x6VxYGldICC2GsojCzojiOaEJxZFvKS+cReLDzVzvYkSCaPoHBYj4OQhnc5R+6TRh55z7Tno42rTWD4ajTgjg3ORxCLcsV1dbXObeF9cRR2rfcPZnDS4mSzfXZikFzzmzamdcjXe2IslAHlNBMDR/+droxYQyjB3gxPCO1q3t+6KC9lSxsIw/g49UmwGeD6HJxhU3RoPqYeWDnvoftzwg+y2e7zTkncD6k2n5RavLPmSpuUPMVdf9RHXdXwG6p2hISaPcuJpHXhUdiMcHC6IS7/6/RCdJg5g3JTtKV7qr++rPEavuUh6AYcCJ/MVeJ6+J7giVNLSDsnO+AJoP+ofgXoXeO34NR5t4B9H3r4EPKeZTrWyD7ChWx85l0Thu+w1n9kgmZKN21fMmibbPCvPuVr3bBpinfG1NO78WpTxiNDDpDYLcUtFrYwbNTlzIz8bWaauC+mPctPpJHA5Km48aunbT1Ccq8e+BXlyiqXk1ogl92CzK4zls="
    #OSSRH_JIRA_PASSWORD
    - secure: "yeiPBBtJJrL6QjWPnvWDbQeu3QtfneAIAvrtcmj6DY6xKYEmNn8MaXJQnX15f9qm5gFb5abWKaOok+cUXHKy0I6Ljz4nJdVtc4EzUVTqZ7UYUL4/qmeb1fxM+K3UfVWgFtgNG5ypdLw2fBEZ1yk+JqBL7Fi/jkQRo2nh3AuwqRN25hK7l4uLyPpx5hiEGboORSGFW/BHts4Ty8Sb3HwTyZErFSRVqKmdF3o+uSipZV2T6N3nIjDcQjs64kpBYXDz7gsXylo3uBzB9/1MSfFdhx8AteLFSRs+9TwcVJO9Hgbo+vaH3RwLN0QSrtTP2vhMhyTYLRjiSpLSg8rnEIk7NF0ZCNha2NEp+22QEHQeTshMZqi5qUumXihoZ9QLaIFY0i/vpzWNZDTzMHzCZacf7ZR3QHyC+ni1l838ZzsvI74GCGGAlIro8n4E/yVhsa7EEqtjGWojOao/J+n7NLUoXIWxBxdjqQIDUAromS1K5A7z4N7ypzFQvAfTAsrZxeyetUJlEgLSyzkF7VeUiYcDCANDBP9nDmF9QWTYbqoi8L+wIPK72TCuZlpdMh7UWUmFX0z2BZR7qv8HkHgdzE8DRLYBTKsngSqud31X97W7Bx8BXbSdnQduMppkezwVmWKxh85NTbLKpCJJGBSbIaYqqdMUZ89M8uzUMfG3Qf7upjU="
    #signing key
    #GPG_KEY_NAME
    - secure: "jdbYENA/z8U34tnkNl5azLMq46zjDaMegiXA1Cn85KK5IGX9Cr+03/v/6qPKRGFrnNVgoRi/znRcrz3N+VdjlwONVxX08e5NdOdXHqn14ZgxExioeIO7M8RGXlGzMw8PNzRP+HNEEbHPS5q02pKykLjHG76RFSJWQ7nZgvcMjZaoP1ub1OX+7EiT/HhKBbwH6xJMxVaV28+sYRnCTDXNKKNPsM+xuTx3t3u3CoMdIGVEIcSxKDAg1U4aHrpFfarj4Ft3o2rTqruJAR0AKMJ0ZpfDO3apjW2On7Khvy69KFm1oXQRbYf3AGnql1rQCfGqK5N55LBiYJMErZx9j/K/CZjWO48+W/e0wpUdcG9GPNKxfUORy4y0JfV3fB7WvO1IXq13U2Xnfka5fDhJy0W8BGVipJHcmueJ8X7Uhv7O3OjwZqq9NvX2OPE+HZEGMjg/4U5zuw4agoIknVabY72u8a9SNGXE+SCIxZ35P6zuE95gFsPdaPDMJc0+v++QjvgK7eCe8OV3O7FukSBXdlVJHrsd47GZ9F5xmL2XoU6tJ/eVYLXyFrA3jnY5cAiPjhTnfIsaLlNjFnk1yRxFKcQvzWEBn4m4cHP9g71NG0T1mxA5XjyK0uzTmTCingmbv6WAm6wC/VUGX5fTxIuFdktw7ka3Q38tP+VO8otgdcDqNtw="
    #GPG_PASSPHRASE
    - secure: "V7+hWYeSf0IsUmSxLwWgvjEEa7aC01w8loRtma2+uFRyLrY0VMRKX0U4zjJaQfwusgeNTRYd5DKtLfS8i9z7L/mkj4P9q69YNqws0DTvD9Akex2v7OF0ddEmIUDY2ThX0ulOd8zg9P0+qbVVlPI15V0AC4PFCjhctP/Bref+irQrRzYws7c9ay3l0tDGrB24x3SWiyOCKt6cJIfwBtAI29FPRWBjlpzBYia8wdDbHb9YD0BsMaZYIKho8nbBClS9kIlolDxzD1OP6yJsEhx7caZqtda75yIw1jFD7fJE4OuWn/PLiYlTQZsr2ka3wrSzrsLL5JqzVLZxo487Labh9x/kUtCi91Y1/EEpxCinjBYD9cPEuaVefebPrtlp0fvUsOwRFhTJLzJxpyKn9uGhufzhSGgaoHDCJvlWxHHdl5ZSAXF1rpj43Cpc4HE9wa+lNovQTPIs0wDfufQSslSZ6UKRf7eNE6J/E5spu1tDujT9BIAMNiNBTDkh66o+rKQxcfQyYAzKZ+6afnaOegIm7XwbYCzdosce6jcnbXea8g10IWlhfOakQpChhsIHtdbcir5JTYnuKXWqpN8JcKQQ+I2L9AohSo6XP240Y/RhpEAEIsOBWIxQAYDkIXwJCCEFwTMq73wxT5Prii+GgsQs3q/jIjNjxqka0Cei8IFrUcs="

addons:
  sonarcloud:
    organization: "albertoirurueta-github"
    token:
      secure: "vIkUoYy+yw+Q80Ggcfe52zVWWBHPfvCItrZfNzTx3ze+Byz/KRuUyanK1apqbKdyZMzcZvFayuvMP2i2IWE7ao/f7VE1W5p80SmuPTw8sH6tn/GL4E7y3WUhSrtQ0SkgdWQxIYfz8+GspWxOyp+c8KIF59/ZVgydQbk1LFtWtLU307QlcqKVX4gn1l4rN9tY70sfKN6V5vHfyMPK4/RM2l7SdT+tduifbztpysb486ed0WDAQ868FDuuSk3BW1ldlx8sYSGudc8F58m5kElYld1PIuFck4sOkSXRYvw3y47russHlWNcDHwSsOkI7LOEeKfC56hZhHCbDTeUdyKW2WHLh9E2bAxJCSbdkxAE2JDrE1cxgy7/XaGWXSuBlQtB2cxxz6rX0J8aiujyz/rBPhJGiaaZG2C0CJIqfCDA3sujfrO9pt91rPz3rIyTCOEHpk3j8TJPo2RfjjqfbJ9G6fRg165CXyFNbOGm2IY95nHtd/B1EGNPiiDa3kMP3ckx0wLFX4ydrTFejzKwesuFieFeMttuU74nuh9OVlhBvUy4mdMhiPziaEmNYWSZ4q1Yey1dwXHwqoI50/ccl4gO/xUTxYvOduupn/mMBp9kOpN7NSdE7MrDOsf75hlH0V1nLB4xkT5px99ot9Y3lqh29NH6DvaxrvfwdqDq2KMNZ+o="

#if timeout occurs, add travis_wait as in example below:
#script: travis_wait mvn clean jacoco:prepare-agent install jacoco:report site

#add: -Denvironment=test to activate CI profile to publish into gh-pages
script:
  - travis_wait mvn clean jacoco:prepare-agent install jacoco:report -Denvironment=test -P !build-extras
  - mvn site -Djacoco.skip -DskipTests --quiet -P !build-extras
  - sonar-scanner

cache:
  directories:
    - ~/.m2/repository

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: ./target/site
  on:
    branch: master

after_success:
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh
